
export enum MsgType
{
    BIZ_MSG = 0,
    CTRL_HEART_BEAT = 1,
    CTRL_CONNC_OPEN = 2,
    CTRL_CONNC_CLOSE = 3,
    CTRL_CUSTOM = 4,
    ERR_MSG = 7
}

export enum ExtType
{

    BIZ_MSG_EXT_TYPE_UNICAST = MsgType.BIZ_MSG * 10 + 0,
    BIZ_MSG_EXT_TYPE_BROADCAST = MsgType.BIZ_MSG * 10 + 1,
    BIZ_MSG_EXT_TYPE_MULTICAST = MsgType.BIZ_MSG * 10 + 2,

    CTRL_HEART_BEAT_EXT_TYPE_BASIC = MsgType.CTRL_HEART_BEAT * 10 + 0,

    CTRL_CONNC_OPEN_EXT_TYPE_BASIC = MsgType.CTRL_CONNC_OPEN * 10 + 0,

    CTRL_CONNC_CLOSE_EXT_TYPE_NO_PARAM = MsgType.CTRL_CONNC_CLOSE * 10 + 0,
    CTRL_CONNC_CLOSE_EXT_TYPE_WITH_CAUSE_CODE = MsgType.CTRL_CONNC_CLOSE * 10 + 1,

    CTRL_CUSTOM_EXT_TYPE_0 = MsgType.CTRL_CUSTOM * 10 + 0,
    CTRL_CUSTOM_EXT_TYPE_1 = MsgType.CTRL_CUSTOM * 10 + 1,
    CTRL_CUSTOM_EXT_TYPE_2 = MsgType.CTRL_CUSTOM * 10 + 2,
    CTRL_CUSTOM_EXT_TYPE_3 = MsgType.CTRL_CUSTOM * 10 + 3,

    ERR_MSG_EXT_TYPE_CODE = MsgType.ERR_MSG * 10 + 0,
    ERR_MSG_EXT_TYPE_CODE_WITH_CAUSE = MsgType.ERR_MSG * 10 + 1,
    ERR_MSG_EXT_TYPE_CODE_WITH_AGENT_ID = MsgType.ERR_MSG * 10 + 2,
    ERR_MSG_EXT_TYPE_CODE_WITH_AGENT_ID_AND_CAUSE = MsgType.ERR_MSG * 10 + 3,	
}