/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameManager from "./GameLogic/Manager/GameManager"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1600;
    static height:number=900;
    static scaleMode:string="fixedwidth";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="StartScene.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("GameLogic/Manager/GameManager.ts",GameManager);
    }
}
GameConfig.init();